### ISSUE TITLE
请教个设置请求头的问题

### ISSUE THREAD

**Issue by mercyxu** [shmilyQin/RxSwiftLearn#1]
![image](https://github.com/user-attachments/assets/dc4af6a7-20d4-4327-aa02-71c90113d664)
![image](https://github.com/user-attachments/assets/a11708de-f112-45cb-8fef-0d77edb03b5f)
![image](https://github.com/user-attachments/assets/b7d3c030-c18a-40cc-9437-39ba41539063)
你好，请教一个问题，我使用Demo修改请求的URL，并设置了请求头，就会无法请求，请求头传nil就没问题，知道这是哪里的问题吗。url:https://testwalletapi.orex.work

**Comment by shmilyQin** [comment]
我试了下是可以的嘞。
![image](https://github.com/user-attachments/assets/03e26133-a63a-46f9-9e01-fe8991714943)
![image](https://github.com/user-attachments/assets/fc2b1d33-0b26-4dfd-856c-61753b64fe22)

**Comment by mercyxu** [comment]
<img width="505" alt="image" src="https://github.com/user-attachments/assets/73058b42-ade0-49c9-9795-0feb5154a34a">
请试一下上面的写法就能复现，1和2有什么区别吗

**Comment by shmilyQin** [comment]
如果你想初始化一个空字典，应该用var header: [String: String] = [:] 这样就行
